### ISSUE TITLE
ansible升级后无法执行

### ISSUE THREAD

**Issue by ningjianghang** [HuaweiSwitch/CloudEngine-Ansible#18]
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Dm9NQB/ansible_module_ce_command.py", line 269, in <module>
    main()
  File "/tmp/ansible_Dm9NQB/ansible_module_ce_command.py", line 204, in main
    supports_check_mode=True)
  File "/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/network.py", line 134, in __init__
  File "/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/network.py", line 170, in connect
  File "/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/cloudengine.py", line 221, in connect
  File "/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/shell.py", line 157, in send
TypeError: string indices must be integers, not str

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Dm9NQB/ansible_module_ce_command.py\", line 269, in <module>\n    main()\n  File \"/tmp/ansible_Dm9NQB/ansible_module_ce_command.py\", line 204, in main\n    supports_check_mode=True)\n  File \"/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/network.py\", line 134, in __init__\n  File \"/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/network.py\", line 170, in connect\n  File \"/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/cloudengine.py\", line 221, in connect\n  File \"/tmp/ansible_Dm9NQB/ansible_modlib.zip/ansible/module_utils/shell.py\", line 157, in send\nTypeError: string indices must be integers, not str\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

**Comment by ningjianghang** [comment]
文档中的
ansible --version ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
￼
升级到了 2.3.1.0 就有问题了
 ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

**Comment by QijunPan** [comment]
ansible 2.3 请用这个分支代码安装，安装方法和路径和ansible 2.2不一样。
```
https://github.com/HuaweiSwitch/CloudEngine-Ansible/tree/devel-2.3
```
注意：里面有安装脚本install.sh，依赖python-pip工具，如果没安装python-pip，请修改一下安装脚本（调整一下安装路径即可）。
