### ISSUE TITLE
Fail when use ce_bgp.py to create a new process on CE switch

### ISSUE THREAD

**Issue by ijustQqh** [HuaweiSwitch/CloudEngine-Ansible#39]
when I try to create a new bgp process on CE switch use ce_bgp.py , error occur:

=======================================================
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Cn1iX4/ansible_module_ce_bgp.py", line 2356, in <module>
    main()
  File "/tmp/ansible_Cn1iX4/ansible_module_ce_bgp.py", line 2172, in main
    asnumber_exist = bgp_enable_exist[0][0]
IndexError: list index out of range
fatal: [129.9.80.30]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Cn1iX4/ansible_module_ce_bgp.py\", line 2356, in <module>\n    main()\n  File \"/tmp/ansible_Cn1iX4/ansible_module_ce_bgp.py\", line 2172, in main\n    asnumber_exist = bgp_enable_exist[0][0]\nIndexError: list index out of range\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 245
}
        to retry, use: --limit @/usr/huawei_ansible/set_leaf.retry
=======================================================

the error seems about bgp_enable_exist[0][0]  list index out of range in ce_bgp.py line 2172:

![image](https://user-images.githubusercontent.com/39176413/39901707-27f3402e-5505-11e8-8e92-e71eec38a452.png)

about get_bgp_enable function: 
![image](https://user-images.githubusercontent.com/39176413/39901743-528c6a86-5505-11e8-82e8-33eb52e824b9.png)

seems not correct

the netconf result is:
![image](https://user-images.githubusercontent.com/39176413/39901774-9279b798-5505-11e8-82cb-16a255e44543.png)

**Comment by kpostrup** [comment]
I have had to implement a workaround to use `ce_config` instead. Too bad this module is in such a state that it cannot be used.
