### ISSUE TITLE
关于ce_vrf模块报错问题

### ISSUE THREAD

**Issue by mingtao-li** [HuaweiSwitch/CloudEngine-Ansible#74]
YMAL脚本：
- name: CloudEngine command test
  hosts: CE_6851
  connection: local
  gather_facts: no
  vars_files:
      - creds.yaml
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli
 tasks:
 - name: Config a vpn install named vpna, description is test
    ce_vrf:
      vrf: vpna
      description: test
      state: present
      provider: "{{ cli }}"

ansible verion: 2.8.5
python version:  3.7.3

**Comment by mingtao-li** [comment]
报错信息：

PLAY [CloudEngine command test] ********************************************************************************************************************************************

TASK [Config a vpn install named vpna, description is test] ****************************************************************************************************************
fatal: [10.191.140.8]: FAILED! => {"msg": "Could not open connection, possibly due to unacceptable SSH subsystem name."}

PLAY RECAP *****************************************************************************************************************************************************************
10.191.140.8               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by mingtao-li** [comment]
ce_config   ce_acl 模块可以正常使用

**Comment by yuandongxx** [comment]
Can you comment your ansible version information and test log information with '-vvvv'?

**Comment by liukun2348** [comment]
@mingtao-li  我们复验了这模块是没有问题的。
你那边能贴 一些具体的日志信息和版本信息吗？我们好复现定位一下问题。
谢谢！

**Comment by mingtao-li** [comment]
> Can you comment your ansible version information and test log information with '-vvvv'?

The full traceback is:
Traceback (most recent call last):
  File "/root/miniconda3/bin/ansible-connection", line 104, in start
    self.connection._connect()
  File "/root/miniconda3/lib/python3.7/site-packages/ansible/plugins/connection/netconf.py", line 322, in _connect
    ssh_config=ssh_config
  File "/root/miniconda3/lib/python3.7/site-packages/ncclient/manager.py", line 177, in connect
    return connect_ssh(*args, **kwds)
  File "/root/miniconda3/lib/python3.7/site-packages/ncclient/manager.py", line 143, in connect_ssh
    session.connect(*args, **kwds)
  File "/root/miniconda3/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 516, in connect
    raise SSHError("Could not open connection, possibly due to unacceptable"
ncclient.transport.errors.SSHError: Could not open connection, possibly due to unacceptable SSH subsystem name.

fatal: [10.191.140.8]: FAILED! => {
    "msg": "Could not open connection, possibly due to unacceptable SSH subsystem name."
}

**Comment by mingtao-li** [comment]
> @mingtao-li 我们复验了这模块是没有问题的。
> 你那边能贴 一些具体的日志信息和版本信息吗？我们好复现定位一下问题。
> 谢谢！

ansible verion: 2.8.5
python version: 3.7.3


报错信息：
PLAY [CloudEngine command test] ********************************************************************************************

TASK [Config a vpn install named vpna, description is test] ****************************************************************
fatal: [10.191.140.8]: FAILED! => {"msg": "Could not open connection, possibly due to unacceptable SSH subsystem name."}

PLAY RECAP *****************************************************************************************************************
10.191.140.8               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
