### ISSUE TITLE
您好：帮忙看看这个报错？

### ISSUE THREAD

**Issue by Founderbn2014** [HuaweiSwitch/CloudEngine-Ansible#80]
//华为CE设备示例      

inventory文件
cat /etc/ansible/hosts 
[cloudengine]
ce1 ansible_host=10.100.2.11

playbook：
---
- name: config HuaWei CE network
  hosts: cloudengine
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      port: 22
      username: test
      password: test@123
      transport: cli

  tasks:

    - name: config a layer3 interface
      ce_interface:
        interface: 10GE1/0/47 
        description: "test123"
        mode: layer3
        provider: '{{ cli }}'
报错：
TASK [config a layer3 interface] ********************************************************************************************************************************************
task path: /etc/ansible/ce_l3_int.yaml:15
<10.100.2.11> using connection plugin netconf (was local)
<10.100.2.11> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.100.2.11> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.100.2.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061 `" && echo ansible-tmp-1589961066.59-167948767092061="` echo /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061 `" ) && sleep 0'
<ce1> Attempting python interpreter discovery
<10.100.2.11> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.100.2.11> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/cloudengine/ce_interface.py
<10.100.2.11> PUT /root/.ansible/tmp/ansible-local-11910kUXaFg/tmpz10nlN TO /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py
<10.100.2.11> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/ /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py && sleep 0'
<10.100.2.11> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py && sleep 0'
<10.100.2.11> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.cloudengine.ce_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py", line 897, in <module>
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py", line 893, in main
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py", line 804, in work
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py", line 406, in get_interface_dict
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/cloudengine/ce.py", line 379, in get_nc_config
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/common/netconf.py", line 76, in __rpc__
  File "/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/common/netconf.py", line 108, in parse_rpc_error
ansible.module_utils.connection.ConnectionError: Exception('command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.',)

fatal: [ce1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1589961066.59-167948767092061/AnsiballZ_ce_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.cloudengine.ce_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py\", line 897, in <module>\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py\", line 893, in main\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py\", line 804, in work\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/modules/network/cloudengine/ce_interface.py\", line 406, in get_interface_dict\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/cloudengine/ce.py\", line 379, in get_nc_config\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/common/netconf.py\", line 76, in __rpc__\n  File \"/tmp/ansible_ce_interface_payload_J6tK5_/ansible_ce_interface_payload.zip/ansible/module_utils/network/common/netconf.py\", line 108, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: Exception('command timeout triggered, timeout value is 30 secs.\\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.',)\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************************************
ce1                        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by lonely123** [comment]
你好，我是华为交换机ansible开发人员，通过你的报错信息，初步判断为连接问题，你可以尝试在task中添加timeout,来增加超时等待时间，例如
name: config a layer3 interface
ce_interface:
interface: 10GE1/0/47
description: "test123"
mode: layer3
timeout: 100
provider: '{{ cli }}'
